### PR TITLE
Update SCSS files for better helper file controls 

### PR DESCRIPTION
**Pull request by michaelbourne**
This PR aims to create better color control through use of the _config.scss file by greatly reducing the number of hardcoded hex colors found in the theme. It also moves reusable styles like form elements into helper mixins. This set the stage for creating better Gutenberg and Admin stylesheets without duplicating styles found elsewhere.

### CODE REVIEW

**Comment by michaelbourne** [comment]
In reference to #29 , a small update to scss files. THis should leave the default theme nearly identical to the previous styles, with slight changes to hardcoded colors moving to lighten() or darken() functions based of their context color.

**Comment by ronilaukkarinen** [comment]
Hi @michaelbourne! Great changes, these are exactly the ones we have been planning to do, so thank you very much. Only thing I'd change here is those lighten colors. If one would change $color-body to a lighter one in the project and then there's lightened body color, it will be too light. So can you add those to variables as well? After this I will merge your changes.

**Comment by michaelbourne** [comment]
You bet. Changed that, tweaked some comments to better reflect usage.

**Comment by michaelbourne** [comment]
Outdated as per newest Air releases.

**Comment by ronilaukkarinen** [comment]
Completely forgot about this, sorry Michael! We've been very busy.

**Comment by michaelbourne** [comment]
No worries, you've been very busy indeed. When the dust settles, I'll see if any of my changes are still worth sending a PR in.

**Pull request closed without merging**
