### PR TITLE
Fix navigation

### LINKED ISSUE #26: Keyboard support fix on mobile menu
On small screens, tabbing after the last link, will return back to the close button – which is great. 

However, if your last link contains a submenu  button, tabbing after it will not return focus on the close button. Instead, it will focus on the content behind the opened mobile menu.

### PR DESCRIPTION
**Pull request by michaelbourne**
Refactor code (variables, functions, scope, events, triggers, undeclared variables), fix focus trap, fix Nav toggle text replacement. Small css tweak to stop menu overflow.

Fixes #26 

Gulp not ran as one of the dependencies in the new theme causes issues on my Windows machine, source files updated only.

Tested on my end to work well on all supported browsers, seems to fix all the issues we had with nav, but I would love another set of eyes testing it.

### CODE REVIEW

**Comment by ronilaukkarinen** [comment]
Nice! I'll test this out soon. Build seem to fail due to eslint and stylelnit errors, [see report](https://travis-ci.com/github/digitoimistodude/air-light/jobs/500307430). Do you use stylelint and eslint inside your editor? You can even autoformat on save. By formatting files directly on editor you get probably most of those fixed, alphabetical orders in CSS and indents in JS at least. I can check out those also while testing but just FYI.

**Review by ronilaukkarinen — CHANGES_REQUESTED** [review]
Closing navigation with ESC produces an error:

```
front-end.js?ver=1619068011:formatted:306 Uncaught TypeError: Cannot read property 'className' of null
    at HTMLAnchorElement.x (front-end.js?ver=1619068011:formatted:306)
    at HTMLButtonElement.handler (jquery.js?ver=3.5.1:5647)
    at HTMLButtonElement.dispatch (jquery.js?ver=3.5.1:5429)
    at HTMLButtonElement.elemData.handle (jquery.js?ver=3.5.1:5233)
    at Object.trigger (jquery.js?ver=3.5.1:8715)
    at HTMLButtonElement.<anonymous> (jquery.js?ver=3.5.1:8793)
    at Function.each (jquery.js?ver=3.5.1:381)
    at jQuery.fn.init.each (jquery.js?ver=3.5.1:203)
    at jQuery.fn.init.trigger (jquery.js?ver=3.5.1:8792)
    at HTMLAnchorElement.<anonymous> (front-end.js?ver=1619068011:formatted:168)
```

This does not happen in the version before PR. I would advice to test out once again with ESC, arrow keys, enter, toggling, tabbing, both mobile and desktop versions.

Also please fix the [eslint errors](https://travis-ci.com/github/digitoimistodude/air-light/jobs/500307430).

**Comment by ronilaukkarinen** [comment]
> Gulp not ran as one of the dependencies in the new theme causes issues on my Windows machine, source files updated only.

Gulp ran successfully here (Win/Mac). Can you point out which dependencies cause problems and what kind of problems so I could be of help.

**Comment by michaelbourne** [comment]
Did you run gulp on this PR to build the production JS? It looks like you didn't, hence the error. I was inly updating source files as I don't have Python installed, so I couldn't use Fibers. No matter.

I've installed Python so I could run your new gulp file. Linted errors are clear. Now I have a new error for setLazyLoadedFigureWidth not being defined, looks like webpack isnt replacing that variable during the build.

**Comment by ronilaukkarinen** [comment]
Yes I did run gulp.

I now got the latest version of your branch and ran gulp tasks again and got the same problem with undefined function. This is probably in our end. Althought the latest version 7.2.3 doesn't have this issue we haven't done anything to gutenberg-helpers.js in the meantime.

Is your branch based on as latest as possible version of Air-light? Or not that old? I see the 7.2.2 version at least but it still shows "Your branch is ahead of 'origin/michaelbourne-master' by 895 commits." so I'm kinda confused here.

Will test more today.

**Review by ronilaukkarinen — COMMENTED** [review]
Pro tip: By the way if you use VSCode, my plugin stylefmt will format these _on save_: https://github.com/ronilaukkarinen/vscode-stylefmt

You also need vscode-stylelint: https://github.com/stylelint/vscode-stylelint and [this setting](https://github.com/ronilaukkarinen/vscode-settings/blob/4529a7a925a88516343b5d7ab628aba76b57f2e5/settings.json#L194) and [this setting](https://github.com/ronilaukkarinen/vscode-settings/blob/4529a7a925a88516343b5d7ab628aba76b57f2e5/settings.json#L181). 👍

**Comment by ronilaukkarinen** [comment]
Works well, merged! Thank you so much @michaelbourne!

**Pull request merged**
