### PR TITLE
Add hover style to ACF block previews

### PR DESCRIPTION
**Pull request by Niq1982**
This improves the overall usability of ACF blocks in block editor. When user hovers a ACF block on preview mode, the cursor is changed to edit icon to indicate that clicking this area will open the block's edit mode rather than reacting with the actual content, like buttons or links. Also the block is shaded with white, so user can see the actual block area going to be edited. 

Screenshot 2021-06-01 at 11 41 30

### CODE REVIEW

**Comment by ronilaukkarinen** [comment]
In my opinion this not very usable/accessible and to be honest more of annoyance, at least with the dominating overlay.

Also something to think of:

- What do we gain by showing the block name here? We know what we are editing because we see it visually
- We know already we are in the editor so there is no need for cursor - this is also just a distraction
- User gets easily used to previews and learns quickly one can edit them just by clicking them

This change also makes hovering actual links and buttons (or other interactive elements) impossible because of the overlay.

In my opinion it's perfectly okay to "go with Gutenberg" here and there is no need to add extra hovers effects or labels to the previews. I vote no for this PR for now.

**Comment by Niq1982** [comment]
For me the ACF blocks showing **no indication at all** when hovering a clickable area is an UX antipattern and annoying as hell. And not at all accessible. But have it your way.

**Comment by ronilaukkarinen** [comment]
This is not just "my way", I think in this matter of detail/preference where honestly we should follow the official decisions. There have been plenty of [discussions about the matter](https://github.com/WordPress/gutenberg/issues?q=is%3Aissue+is%3Aopen+hover+indicator) most recently in [this](https://github.com/WordPress/gutenberg/issues/31283#issuecomment-832469558) and [this](https://github.com/WordPress/gutenberg/issues/30777) issue.

I agree with both jasmussen's and carolinan's opinions:

> We've tried it in the past, and removed it quickly as it was too noisy.

> The hover style can also be difficult to see on colored and dark backgrounds.

There are many challenges with this approach and as a minimalist I prefer less "noisy" approach. We CAN and should discuss this further but for me it's a really low-low-prio thing to do at this point.

**Comment by Niq1982** [comment]
If you would have bothered to read my description or try the PR, you'd realize that this is about ACF blocks and it has nothing to do with regular block editor blocks hover states, to which your links are pointing.

**Comment by ronilaukkarinen** [comment]
I did read it and gave it a real thought, I'm well aware this is about ACF blocks for us. What I meant is that the same rule principles should apply to these blocks as well. Editing is even more obvious in ACF blocks because when clicking the blocks the block shifts to "edit mode" so user learns very fast how editing works.

**Comment by Niq1982** [comment]
Here's the thing: The ACF blocks don't work with the same rule principles as the core blocks when you look at it from UX perspective. Not at all. 

My intention was actually to bring ACF block editing experience _closer_ to the core block editing experience and let the user know what the user is doing before clicking. As they can see now when they are interacting with core block fields. 

Go read any user experience study and see how most annoying ui patterns involve something unexpected happening from interaction. It doesn't matter if user is used to it or not, it's still an antipattern and should be avoided.

**Pull request closed without merging**
