### PR TITLE
Add aria labels to links with img inside, fixes #111

### LINKED ISSUE #111: External-link.js: If link contains img, get alt tag content to aria-label
For example:

``` html
<a href="https://www.google.com">
  <img src="https://www.google.fi/images/branding/googlelogo/2x/googlelogo_color_160x56dp.png" alt="Google" />
</a>
```

This is currently outputting as:

``` html
<a href="https://www.google.com" aria-label="External site: " class="is-external-link">
  <img src="https://www.google.fi/images/branding/googlelogo/2x/googlelogo_color_160x56dp.png" alt="Google" />
</a>
```

It should be like this:

``` html
<a href="https://www.google.com" aria-label="External site: Google" class="is-external-link">
  <img src="https://www.google.fi/images/branding/googlelogo/2x/googlelogo_color_160x56dp.png" alt="Google" />
</a>
```

If there's target="_blank", it should be:

``` html
<a href="https://www.google.com" aria-label="External site: Google, opens in a new window" class="is-external-link" target="_blank">
  <img src="https://www.google.fi/images/branding/googlelogo/2x/googlelogo_color_160x56dp.png" alt="Google" />
</a>
```

Changes needed in [external-link.js](https://github.com/digitoimistodude/air-light/blob/1a025faad3a7b730f0e742ca3aee3c1c5b3b16e5/js/src/modules/external-link.js) for it to be able to recognize the link type and parse the alt.

### PR DESCRIPTION
**Pull request by Niq1982**
When a link doesn't have any text content and has only img elements inside, tries to get the img alt texts to aria labels. Works both in internal and external links.

### CODE REVIEW

**Review by ronilaukkarinen — APPROVED** [review]

**Comment by samikeijonen** [comment]
Not sure I understand this issue?

Is it about this scenario `<a href="#">About us</a>`.

**Comment by ronilaukkarinen** [comment]
@samikeijonen This is a PR that fixes the issue in a scenario where link has to have indicator it leads to external site while link content is only image without any labels in the link. It's explained [here](https://github.com/digitoimistodude/air-light/issues/111).

**Comment by samikeijonen** [comment]
Got it!

What comes to announcing "external site", that's not a WCAG requirement. But probably doesn't hurt either.

There is a rule though that aria-label needs to start with the same text as visible text. For example:

`<a href="#" aria-label="Dude - fantastico!">Dude</a>`.

**Comment by ronilaukkarinen** [comment]
> What comes to announcing "external site", that's not a WCAG requirement. But probably doesn't hurt either.

@samikeijonen I've seen Success Criterion 2.4.4: Link Purpose and other similar rules interpreted many times as so that the external links need to have an indication about the link leading to external site and especially if it has for any reason target="_blank". This is why we have

- Visual arrow as indicator if the link leads to outside site
- aria-label that contains "External-site: _the text of the link_"
- If there's target _blank, aria-label="External-site: _the text of the link_, opens in a new window"
- All the previously mentioned localized accordingly

Perhaps some unnecessary but kinda bulletproof IMHO.

**Comment by samikeijonen** [comment]
Yep, when using `target="_blank"` then informing that in link text for all is good.

But I was thinking about basic link like this:

Search more in `<a href="https://www.google.com/">Google</a>`. Or just `<a href="https://www.google.com/">Google search</a>`.

Those are clear link text without telling extra information and link purpose is therefor clear.

**Comment by ronilaukkarinen** [comment]
Yeah, I figured that much out. For these links we have programmatically and visually indicators as well just in case. In outputted HTML it's like this:

`<a href="https://www.google.com/" aria-label="External site: Google">Google (+ visual arrow here as SVG)</a>`

We can't rely that the customer adds very descriptive text contents for these links so this is usually good thing in all levels.

**Comment by samikeijonen** [comment]
In that case I recommend switching the order so that actual link and aria-label starts with the same wording:

`<a href="https://www.google.com/" aria-label="Google: External site">Google (+ visual arrow here as SVG)</a>`

**Comment by ronilaukkarinen** [comment]
The order is derived from some expert's example already 😄 but that's a good recommendation and rather easy to do: https://github.com/digitoimistodude/air-light/blob/a9097e9de3be6b15e1a1bd7a7af9c7576dc64460/js/src/modules/external-link.js#L90

**Pull request merged**
